apiVersion: apps/v1
kind: Deployment
metadata:
  name: distributed-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: distributed-app
  template:
    metadata:
      labels:
        app: distributed-app
    spec:
      containers:
      - name: frontend
        image: distributed-app-frontend
        ports:
        - containerPort: 3000
      - name: backend
        image: distributed-app-backend
        ports:
        - containerPort: 3000